# Generated by Django 5.1.5 on 2025-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='scroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
