# Generated by Django 5.1.5 on 2025-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_scroll_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
