# Generated by Django 5.2 on 2025-04-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='usename',
        ),
    ]
