# Generated by Django 5.2 on 2025-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_usename_log_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='log',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
