# Generated by Django 5.2 on 2025-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_log_password_alter_log_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_form',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
