# Generated by Django 5.2 on 2025-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_abt1_slug_abt2_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abt1',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='abt2',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
