# Generated by Django 5.1.5 on 2025-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_scroll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='count',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
