# Generated by Django 5.2 on 2025-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_m_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_form',
            name='number',
        ),
        migrations.AddField(
            model_name='m_form',
            name='message',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='m_form',
            name='subject',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
