# Generated by Django 5.2 on 2025-04-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_user_log_usename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='usename',
            new_name='username',
        ),
    ]
