# Generated by Django 5.2 on 2025-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_form',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
