# Generated by Django 5.2 on 2025-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_booking_is_seen_m_form_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
