# Generated by Django 5.2 on 2025-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_item_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='abt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/abt')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='abt2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/abt')),
                ('details', models.TextField()),
            ],
        ),
    ]
