# Generated by Django 5.2 on 2025-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_abt1_abt2'),
    ]

    operations = [
        migrations.AddField(
            model_name='abt1',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='abt2',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
